### ISSUE TITLE
TOPS-10 SUPDUP

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/supdup#14]
@WestfW wrote to alt.sys.pdp10:
> Spent most of my time on ITS via  a tops10 (with local terminals at a whopping 2400bps!) running SUPDUP (had to write the SUPDUP program first, of course!) The SUPDUP client I wrote was SO much faster than the tops10 telnet client

I wonder if this SUPDUP can be found today?

**Comment by WestfW** [comment]
I suspect it's on one of my "might-as-well-be-unreadable" 9track tapes.  It doesn't seem to be one of the pieces of source code that followed me around after college...
I don't think it was actually very interesting; this was pre-TCP, and most of the speedup came from using a programmatic NCP connection with a bigger "allocation" (?) than the default TTY/NVT mapping that tops10 implemented for telnet back then - essentially the equivalent of opening the connection with a bigger window.  It may have gained a little bit by doing local processing of the display manipulation, and understanding our weird local terminals better than ... what was that tool that ran on top of ITS that translated the native display codes into many terminals?  CRTSTY or something like that?

**Comment by larsbrinkhoff** [comment]
Yes, CRTSTY is the name.

Thanks for the information!
