### ISSUE TITLE
Gotta merge them all!

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/supdup#2]
Hello everyone,

I have checked in branches for some of the C supdup versions.  There's one for @bictorv, one branched off that for @wsgac.  The KLH10 code is in a separate branch until I figure out how it relates to the others.

I'll take other versions if I can find them.  I believe @ams has one.

Other supdup hackers out there?  @MMcM, @leighklotz?

**Comment by larsbrinkhoff** [comment]
@dabridgham of course.

**Comment by larsbrinkhoff** [comment]
@Richard-Mlynarik

**Comment by dabridgham** [comment]
Yeah, somewhere around here I have a version of the client I modified to compile on Linux starting from what was included with the KLH10 distribution I picked up.  My general impression, last I looked at the code, was that the whole thing could use a good de-crufting as well as the work needed to make it compile cleanly across BSD, Linux, and MacOS.

**Comment by larsbrinkhoff** [comment]
Björn's version works fine on Linux, and @wsgac made it work in OpenBSD.

**Comment by dabridgham** [comment]
Looks like the sources I have are Björn's so I don't have changes for you after all.

**Comment by MMcM** [comment]
Björn's branch has the only patch I remember, having to do with termcap %p incompatibility in Debian ncurses.

**Comment by larsbrinkhoff** [comment]
Looks like Björn's version (and thus all others) is based on the one from KLH10 2.0a.

I have now made a revision tree that reflects the history.  @bictorv or @ams, do you have the 2005 Victorian version?  I only have the one from 2010.

I have yet to merge in the changes from KLH10 2.0h.  To make things worse, it has both a supdup.c and a supdup.c-1.

**Comment by larsbrinkhoff** [comment]
Was @romkey involved with the TTYLOC code?

**Comment by bictorv** [comment]
I'm not sure what you mean by "2005 Victorian version"? "Mine" is, as you say, based on the 2.0a version, and if you have "my" latest, is it really interesting to have the one from 2005 (likely with some old bug)? But I could look for it, of course.

**Comment by larsbrinkhoff** [comment]
I saw a comment in supdup.c that there were changes in 2010 and 2005-2004.  Not, it not very important to have all revisions.  It's just that I have a script to automate the process of making a git repository with all revisions and branches.  I wanted to include all authors, rough timestamps, and major changes.  The 2010 change sememed unrelated to the ones from 2005, so it could make sense to have them as separate commits.

**Comment by romkey** [comment]
Any supdup code I wrote would have been for PC/IP under MS-DOS or possibly for a BSD-based supdup server. But it's been so long I can't actually remember if I actually worked on those. :)

**Comment by larsbrinkhoff** [comment]
This is mostly done now.  All versions except klh is merged into master.
