### ISSUE TITLE
Compilation failure on OpenBSD

### ISSUE THREAD

**Issue by ams** [PDP-10/supdup#25]
FWIW, this (#23 and #22) breaks on OpenBSD.  Mostly due to the fact that -lresolv doesn't exist there (nor on some other BSDs), normally these days the libresolv stuff is provided directly by libc both on BSDs and GNU systems but OS X seems to not have followed suite?  Dynamically adding -lresolv to the linker line is slightly tricky to do in some form of portable Make -- since everyone wants to be special.

_Originally posted by @ams in https://github.com/PDP-10/supdup/pull/23#issuecomment-698755348_

**Comment by ams** [comment]
(Another option is that I just make packages for OpenBSD then I can stop caring if I need to write make or gmake)

**Comment by larsbrinkhoff** [comment]
If you can use gmake on OpenBSD, that might be an easy way out.

**Comment by larsbrinkhoff** [comment]
@gwright83 has made some changes for FreeSBD which maybe fixes OpenBSD too?

**Comment by gwright83** [comment]
The change allows me to build supdup (as part of ITS) on my FreeBSD gitlab-CI runner.  It still requires gmake, but that is not uncommon and I'm willing to live with it.

If it works on OpenBSD as well, I can submit a pull request.

**Comment by larsbrinkhoff** [comment]
@gwright83, please do!
