### ISSUE TITLE
supdupd: The result of a left shift is undefined when the left operand is negative.

### ISSUE THREAD

**Issue by johnsonjh** [PDP-10/supdup#28]
* [supdupd.c, line 1238, col 17](https://github.com/PDP-10/supdup/blob/a7683e14034f5efb5cf9c53a9303af8971fce4e7/supdupd.c#L1238): _warning_: The result of the left shift is undefined because the left operand is negative `[core.UndefinedBinaryOperatorResult]`
 ```
  count = -((-1 << 6) | temp[2]);
             ~~ ^
1 warning generated.
 ```  
![1238](https://user-images.githubusercontent.com/61629094/111052866-e80aae00-8456-11eb-9cbe-1c215389a6ca.png)

**Comment by larsbrinkhoff** [comment]
Maybe change to `~0U`?

**Comment by johnsonjh** [comment]
Tested that and it seems OK...

**Comment by johnsonjh** [comment]
Resolved in current master.
